export interface PlanetaryVitalSign {
  id: string;
  category: 'atmosphere' | 'energy' | 'cryosphere' | 'oceans';
  nameEn: string;
  nameFi: string;
  code: string;
  currentValue: number;
  unit: string;
  displayValue: string;
  preIndustrialValue: number;
  preIndustrialDisplay: string;
  safeBoundaryValue: number;
  safeBoundaryDisplay: string;
  status: 'critical' | 'alert' | 'warning';
  trendRate: string;
  instrumentSensor: string;
  institutionSource: string;
  humanPhysicsEn: string;
  humanPhysicsFi: string;
  nepalFloodConnectionEn: string;
  nepalFloodConnectionFi: string;
}

export const PLANETARY_VITAL_SIGNS: PlanetaryVitalSign[] = [
  {
    id: 'co2',
    category: 'atmosphere',
    nameEn: 'Atmospheric Carbon Dioxide',
    nameFi: 'Ilmakehän hiilidioksidipitoisuus',
    code: 'CO₂',
    currentValue: 428.18,
    unit: 'ppm',
    displayValue: '428.2 ppm',
    preIndustrialValue: 280.0,
    preIndustrialDisplay: '280.0 ppm',
    safeBoundaryValue: 350.0,
    safeBoundaryDisplay: '350.0 ppm',
    status: 'critical',
    trendRate: '+2.42 ppm / vuosi',
    instrumentSensor: 'DIR Spectrometer · Mauna Loa Hawaii',
    institutionSource: 'NOAA GML & Scripps Institution of Oceanography',
    humanPhysicsEn: 'Acts as Earth\'s primary thermal blanket. Concentration has surged 52.9% above pre-industrial levels, trapping solar heat energy at planetary scale.',
    humanPhysicsFi: 'Toimii maapallon ensisijaisena lämpöpeittona. Pitoisuus on noussut 52,9 % esiteollisen tason yläpuolelle ja ylittää turvallisen 350 ppm rajan kriittisesti.',
    nepalFloodConnectionEn: 'Excess CO₂ drives atmospheric warming that directly reaches high-altitude Himalayan cirques, melting the subterranean permafrost binding rockfaces at Langtang Lirung.',
    nepalFloodConnectionFi: 'Ylimääräinen hiilidioksidi nostaa vuoriston lämpötilaa ja sulattaa kalliota koossapitävän ikiroudan, mikä laukaisi Langtang Lirungin vuorenseinämän murtumisen.'
  },
  {
    id: 'ch4',
    category: 'atmosphere',
    nameEn: 'Atmospheric Methane Concentration',
    nameFi: 'Ilmakehän metaanipitoisuus',
    code: 'CH₄',
    currentValue: 1933.4,
    unit: 'ppb',
    displayValue: '1 933.4 ppb',
    preIndustrialValue: 722.0,
    preIndustrialDisplay: '722.0 ppb',
    safeBoundaryValue: 800.0,
    safeBoundaryDisplay: '800.0 ppb',
    status: 'critical',
    trendRate: '+11.8 ppb / vuosi',
    instrumentSensor: 'Global Cavity Ring-Down Spectrometry',
    institutionSource: 'NOAA Global Greenhouse Gas Network',
    humanPhysicsEn: 'Over 84 times more heat-trapping than CO₂ over a 20-year window. Surged 168% above the baseline due to fossil leaks, livestock, and thawing permafrost.',
    humanPhysicsFi: '84 kertaa hiilidioksidia voimakkaampi lämmittäjä 20 vuoden jaksolla. Noussut 168 % esiteollisen tason yläpuolelle sulavan ikiroudan ja päästöjen vuoksi.',
    nepalFloodConnectionEn: 'Accelerated near-term warming pulses driven by methane shorten Himalayan winter freezing periods and intensify high-altitude heatwaves.',
    nepalFloodConnectionFi: 'Metaanin voimakas lyhyen aikavälin lämmitysvaikutus lyhentää Himalajan pakkaskausia ja voimistaa vuoriston alkukesän lämpöaaltoja.'
  },
  {
    id: 'temp_anomaly',
    category: 'energy',
    nameEn: 'Global Surface Heating Anomaly',
    nameFi: 'Globaali pintalämpötilan poikkeama',
    code: 'ΔT GLOBAL',
    currentValue: 1.58,
    unit: '°C',
    displayValue: '+1.58 °C',
    preIndustrialValue: 0.0,
    preIndustrialDisplay: '0.00 °C (1850–1900)',
    safeBoundaryValue: 1.5,
    safeBoundaryDisplay: '+1.50 °C (Pariisi)',
    status: 'critical',
    trendRate: '+0.27 °C / vuosikymmen',
    instrumentSensor: 'ERA5 High-Resolution Reanalysis Multi-Satellite',
    institutionSource: 'Copernicus Climate Change Service / ECMWF',
    humanPhysicsEn: 'The running 12-month average has officially transgressed the Paris Agreement 1.5°C guardrail for the first sustained period in human history.',
    humanPhysicsFi: 'Viimeisen 12 kuukauden liukuva keskiarvo on rikkonut Pariisin ilmastosopimuksen 1,5 asteen suojarajan ensimmäistä kertaa ihmiskunnan historiassa.',
    nepalFloodConnectionEn: 'Because mountains heat at 2.1× the global average (Elevation-Dependent Warming), a +1.58°C global world means +2.92°C in the Langtang and Trishuli catchment.',
    nepalFloodConnectionFi: 'Koska vuoristot lämpenevät yli kaksinkertaisella vauhdilla (korkeudesta riippuva lämpeneminen), +1,58 °C maapallolla vastaa +2,92 °C lämpöä Langtangin ja Trishulin huipuilla.'
  },
  {
    id: 'himalaya_edw',
    category: 'energy',
    nameEn: 'Third Pole / Himalaya Local Warming',
    nameFi: 'Himalajan & Kolmannen navan lämpeneminen',
    code: 'HKH TEMP',
    currentValue: 2.92,
    unit: '°C',
    displayValue: '+2.92 °C',
    preIndustrialValue: 0.0,
    preIndustrialDisplay: '0.00 °C',
    safeBoundaryValue: 1.8,
    safeBoundaryDisplay: '+1.80 °C',
    status: 'critical',
    trendRate: '+0.54 °C / vuosikymmen',
    instrumentSensor: 'Automated Weather Stations (AWS) Khumbu-Langtang',
    institutionSource: 'ICIMOD & Ev-K2-CNR Pyramid Laboratory',
    humanPhysicsEn: 'Albedo loss from vanishing snowpack and water vapor feedbacks cause alpine peaks above 4,000m to heat at twice the planetary speed.',
    humanPhysicsFi: 'Lumipeitteen katoaminen ja ilmakehän kosteuspalautteet saavat yli 4 000 metrissä sijaitsevat vuorenhuiput lämpenemään kaksinkertaisella vauhdilla.',
    nepalFloodConnectionEn: 'The direct trigger for permafrost degradation inside the 7,000m ridge of Langtang Lirung that collapsed into the valley.',
    nepalFloodConnectionFi: 'Suora syy kallion sisäisen ikiroutalaastin pettämiseen Langtang Lirungin yli 7 000 metrin harjanteella, joka romahti laaksoon.'
  },
  {
    id: 'eei',
    category: 'energy',
    nameEn: 'Earth\'s Energy Imbalance (EEI)',
    nameFi: 'Maapallon säteilyepätasapaino (EEI)',
    code: 'EEI NET',
    currentValue: 1.48,
    unit: 'W/m²',
    displayValue: '+1.48 W/m²',
    preIndustrialValue: 0.0,
    preIndustrialDisplay: '0.00 W/m²',
    safeBoundaryValue: 0.3,
    safeBoundaryDisplay: '+0.30 W/m²',
    status: 'critical',
    trendRate: '+0.45 W/m² / vuosikymmen',
    instrumentSensor: 'CERES Satellite Radiometer Constellation',
    institutionSource: 'NASA Langley Research Center',
    humanPhysicsEn: 'Earth absorbs 460 Terawatts more solar energy than it radiates into space. Equivalent to the thermal energy of 8.4 Hiroshima nuclear explosions every second.',
    humanPhysicsFi: 'Maapallo imee 460 terawattia enemmän aurinkoenergiaa kuin heijastaa avaruuteen. Vastaa 8,4 Hiroshiman atomipommin lämpöenergiaa joka ikinen sekunti.',
    nepalFloodConnectionEn: 'Continuous thermal forcing fuels extreme atmospheric convective lift, driving intense cloudburst rainstorms onto steep Himalayan river basins.',
    nepalFloodConnectionFi: 'Jatkuva lämpöenergia ruokkii rajua ilmakehän konvektiota ja synnyttää ennennäkemättömiä pilvenpurkauksia jyrkkiin vuoristolaaksoihin.'
  },
  {
    id: 'ocean_heat',
    category: 'oceans',
    nameEn: 'Global Ocean Heat Content (0–2000m)',
    nameFi: 'Valtamerten lämpösisältö (0–2000 m)',
    code: 'OHC 2000m',
    currentValue: 382.4,
    unit: 'ZJ',
    displayValue: '+382.4 ZJ',
    preIndustrialValue: 0.0,
    preIndustrialDisplay: '0.0 ZJ (Vertailu)',
    safeBoundaryValue: 80.0,
    safeBoundaryDisplay: '+80.0 ZJ',
    status: 'critical',
    trendRate: '+15.2 ZJ / vuosi',
    instrumentSensor: 'Argo International Float Array (3,950 Floats)',
    institutionSource: 'NOAA NCEI & International Argo Programme',
    humanPhysicsEn: 'Over 90% of all trapped greenhouse energy is absorbed into oceans (1 Zettajoule = 10²¹ Joules). Ocean heat reached record highs in consecutive years.',
    humanPhysicsFi: 'Yli 90 % ilmastonmuutoksen loukkuun jääneestä lisälämmöstä imeytyy meriin (1 tsettajoule = 10²¹ joulea). Valtameret ovat kuumempia kuin koskaan mitatussa historiassa.',
    nepalFloodConnectionEn: 'Superheated Indian Ocean water fuels intense monsoon moisture plumes that slam into the high Himalayas, triggering cloudbursts.',
    nepalFloodConnectionFi: 'Ylikuumentunut Intian valtameri haihduttaa valtavia monsuunikosteuden virtoja, jotka törmäävät kylmään Himalajaan ja laukaisevat rankkasateita.'
  },
  {
    id: 'himalaya_glacier_loss',
    category: 'cryosphere',
    nameEn: 'Himalayan Glacial Mass Balance Loss',
    nameFi: 'Himalajan jäätiköiden vuotuinen massahävikki',
    code: 'HKH GLACIER',
    currentValue: -79.2,
    unit: 'Gt/yr',
    displayValue: '-79.2 Gt / v',
    preIndustrialValue: 0.0,
    preIndustrialDisplay: 'Tasapaino (0 Gt)',
    safeBoundaryValue: -15.0,
    safeBoundaryDisplay: '-15.0 Gt / v',
    status: 'critical',
    trendRate: 'Hävikki kiihtynyt +65 % v. 2010 jälkeen',
    instrumentSensor: 'ICIMOD Multi-Glacier Geodetic & Space Altimetry',
    institutionSource: 'ICIMOD (Water Towers of Asia Assessment)',
    humanPhysicsEn: 'Glaciers in the Hindu Kush Himalaya lost ice 65% faster between 2010–2020 compared to the previous decade, destabilizing moraines and forming dangerous lakes.',
    humanPhysicsFi: 'Himalajan jäätiköt sulivat 65 % nopeammin vuosina 2010–2020 kuin edellisellä vuosikymmenellä, mikä synnyttää satoja vaarallisia jäätikköjärviä.',
    nepalFloodConnectionEn: 'Directly destabilized Langtang Lirung hanging glaciers, leading to the catastrophic August 2026 ice-rock avalanche down the Trishuli and Lende Khola rivers.',
    nepalFloodConnectionFi: 'Heikensi suoraan Langtang Lirungin roikkuvia jäätiköitä, mikä johti elokuun 2026 katastrofaaliseen jää- ja kivilumivyöryyn Trishulin jokilaaksossa.'
  },
  {
    id: 'greenland_ice',
    category: 'cryosphere',
    nameEn: 'Greenland Ice Sheet Cumulative Loss',
    nameFi: 'Grönlannin mannerjään kumulatiivinen hävikki',
    code: 'GRACE GREENLAND',
    currentValue: -5380,
    unit: 'Gt',
    displayValue: '-5 380 Gt',
    preIndustrialValue: 0,
    preIndustrialDisplay: '0 Gt (Tasapaino)',
    safeBoundaryValue: -1000,
    safeBoundaryDisplay: '-1 000 Gt',
    status: 'critical',
    trendRate: '-275 Gt / vuosi',
    instrumentSensor: 'GRACE-FO Twin Satellite Gravimetry',
    institutionSource: 'NASA Jet Propulsion Laboratory & DLR',
    humanPhysicsEn: '5,380 billion metric tons of continental ice lost since 2000. Every 361.8 Gt of melt raises global mean sea level by 1 millimeter.',
    humanPhysicsFi: '5 380 miljardia tonnia mannerjäätä sulanut vuoden 2000 jälkeen. Joka 362 miljardia tonnia sulanutta jäätä nostaa maailman merenpintaa 1 millimetrin.',
    nepalFloodConnectionEn: 'Both Greenland and the Himalayas share identical cryospheric physics: surface albedo collapse accelerating internal meltwater lubricated flow.',
    nepalFloodConnectionFi: 'Molemmat ilmentävät samaa kryosfäärin fysiikkaa: heijastavuuden heikkeneminen ja sulavesien virtaus jään sisään kiihdyttävät romahdusta.'
  },
  {
    id: 'sea_level_rate',
    category: 'oceans',
    nameEn: 'Global Mean Sea Level Rise Velocity',
    nameFi: 'Merenpinnan nousun vuotuinen nopeus',
    code: 'GMSL RATE',
    currentValue: 4.4,
    unit: 'mm/yr',
    displayValue: '+4.4 mm / v',
    preIndustrialValue: 0.4,
    preIndustrialDisplay: '+0.4 mm / v',
    safeBoundaryValue: 1.5,
    safeBoundaryDisplay: '+1.5 mm / v',
    status: 'critical',
    trendRate: 'Nopeus yli kaksinkertaistunut 1990-luvulta',
    instrumentSensor: 'Sentinel-6 Michael Freilich & Jason-3 Altimeters',
    institutionSource: 'NASA Sea Level Change Science Team / Copernicus',
    humanPhysicsEn: 'Driven by ocean thermal expansion (50%) and land ice melting (Greenland, Antarctica, mountain glaciers 50%). Accelerating non-linearly.',
    humanPhysicsFi: 'Johtuu puoliksi veden lämpölaajenemisesta ja puoliksi maajäätiköiden sulamisesta. Nousuvauhti on kiihtynyt ennätykselliseksi.',
    nepalFloodConnectionEn: 'The pulverized ice and floodwaters that surged through the Trishuli Valley are now entering the Bay of Bengal, permanently lifting high-tide sea levels in the Ganges delta.',
    nepalFloodConnectionFi: 'Trishulin laakson läpi syöksynyt sulamisvesi ja liete päätyvät lopulta Bengalinlahteen nostaen pysyvästi merenpintaa Gangesin suistoalueella.'
  },
  {
    id: 'atmospheric_moisture',
    category: 'atmosphere',
    nameEn: 'Atmospheric Water Vapor Capacity Surge',
    nameFi: 'Ilmakehän kosteudensitomiskyvyn kasvu',
    code: 'CLAUSIUS-CLAPEYRON',
    currentValue: 11.1,
    unit: '%',
    displayValue: '+11.1 %',
    preIndustrialValue: 0.0,
    preIndustrialDisplay: '0.0 % (Baseline)',
    safeBoundaryValue: 4.0,
    safeBoundaryDisplay: '+4.0 %',
    status: 'alert',
    trendRate: '+7.0 % jokaista +1.0 °C lämpenemistä kohti',
    instrumentSensor: 'SSM/I & AMSR-2 Microwave Radiometers',
    institutionSource: 'Remote Sensing Systems (RSS) / NOAA',
    humanPhysicsEn: 'Thermodynamics dictate that warmer air holds 7% more water vapor per 1°C. At +1.58°C, the atmosphere holds ~11% more water, supercharging extreme deluges.',
    humanPhysicsFi: 'Fysiikan lakien mukaan lämpimämpi ilma sitoo 7 % enemmän vesihöyryä jokaista astetta kohden. Ilmakehä toimii kuin supervarautunut sieni.',
    nepalFloodConnectionEn: 'This thermodynamic law caused the monsoon storm over Langtang National Park and the Trishuli basin to dump extreme localized deluges directly onto the destabilized mountain summits.',
    nepalFloodConnectionFi: 'Tämä fysiikan laki aiheutti poikkeuksellisen pilvenpurkauksen Langtangin kansallispuistossa ja Trishulin valuma-alueella juuri ennen vuorenhuipun romahdusta.'
  },
  {
    id: 'ocean_ph',
    category: 'oceans',
    nameEn: 'Ocean Surface Acidification (pH)',
    nameFi: 'Valtamerten pintaveden happamoituminen (pH)',
    code: 'OCEAN pH',
    currentValue: 8.04,
    unit: 'pH',
    displayValue: '8.04 pH',
    preIndustrialValue: 8.25,
    preIndustrialDisplay: '8.25 pH',
    safeBoundaryValue: 8.15,
    safeBoundaryDisplay: '8.15 pH',
    status: 'critical',
    trendRate: '-0.018 pH / vuosikymmen (+30 % happamuus)',
    instrumentSensor: 'HOT Station ALOHA & BATS Autonomous Sensors',
    institutionSource: 'Copernicus Marine Service & NOAA PMEL',
    humanPhysicsEn: 'Oceans have absorbed ~30% of anthropogenic CO2, forming carbonic acid. Acidity has increased 30%, threatening base marine food webs and coral systems.',
    humanPhysicsFi: 'Valtameret ovat imeneet 30 % ihmiskunnan hiilidioksidipäästöistä muodostaen hiilihappoa. Happamuus on lisääntynyt 30 % uhaten merten ravintoketjua.',
    nepalFloodConnectionEn: 'A stark reminder that burning fossil fuels destabilizes both the highest mountain peaks and the deepest oceanic ecosystems simultaneously.',
    nepalFloodConnectionFi: 'Osoittaa, että fossiilisten polttoaineiden polttaminen järkyttää yhtäaikaisesti niin korkeimpia vuoria kuin syvimpiä meriäkin.'
  },
  {
    id: 'arctic_sea_ice',
    category: 'cryosphere',
    nameEn: 'Arctic Sea Ice Minimum Extent',
    nameFi: 'Arktisen merijään minimilaajuus',
    code: 'ARCTIC EXTENT',
    currentValue: 4.26,
    unit: 'M km²',
    displayValue: '4.26 M km²',
    preIndustrialValue: 7.85,
    preIndustrialDisplay: '7.85 M km²',
    safeBoundaryValue: 6.0,
    safeBoundaryDisplay: '6.00 M km²',
    status: 'critical',
    trendRate: '-12.2 % / vuosikymmen (Pinta-ala)',
    instrumentSensor: 'DMSP SSMIS & AMSR-2 Passive Microwave',
    institutionSource: 'National Snow & Ice Data Center (NSIDC) / NASA',
    humanPhysicsEn: 'Thick multi-year ice has collapsed by 75% since 1979. White reflective sea ice is replaced by dark ocean that absorbs 90% of sunlight (albedo feedback).',
    humanPhysicsFi: 'Monivuotisen paksun jään tilavuus on romahtanut 75 % vuodesta 1979. Auringonvaloa heijastava valkoinen jää korvautuu lämpöä imevällä tummalla vedellä.',
    nepalFloodConnectionEn: 'Arctic amplification destabilizes the polar jet stream into sluggish, meandering waves that stall extreme storms over the Himalayas.',
    nepalFloodConnectionFi: 'Arktinen nopea lämpeneminen sekoittaa suihkuvirtaukset ja aiheuttaa jumiutuvia sääilmiöitä, jotka pysäyttävät myrskyt vuoristoon.'
  }
];
